name: flutter_paystack_payment
description: A plugin for Payment through Paystack
version: 0.0.3
homepage: https://github.com/DEVSOG12/flutter_paystack_payment

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  meta: ^1.7.0
  async: ^2.8.2
  # Required for Dart Encryption
  basic_utils: ^3.9.4
  pointycastle: ^3.5.0
  # webview_flutter: ^3.0.0

  # For Requests for Device
  platform_info: ^3.1.0
  device_info_plus: ^3.2.2
  # webview_flutter_web: ^0.1.0+1
  package_info_plus: ^1.3.0
  webview_flutter:
  webview_flutter_web:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0



flutter:
  assets:
    - assets/images/