name: flutter_paystack_payment
description: A plugin for Payment through Paystack made By Oreofe Solarin. 
version: 0.1.4
homepage: https://github.com/DEVSOG12/flutter_paystack_payment

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.19.0
  meta: ^1.9.1
  async: ^2.11.0
  # Required for Dart Encryption 
  basic_utils: ^5.6.0
  pointycastle: ^3.7.3
  # webview_flutter: ^3.0.0

  # For Requests for Device
  platform_info: ^4.0.2
  device_info_plus: ^10.0.1
  package_info_plus: ^6.0.0
  webview_flutter: ^4.2.2
  universal_html: ^2.2.3

  credit_card_scanner: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  matcher: ^0.12.11
  mockito: ^5.2.0



flutter:
  assets:
    - assets/images/
  plugin:
    platforms:
      android:
        default_package: flutter_paystack_payment 
      linux:
        default_package: flutter_paystack_payment          
      windows:
        default_package: flutter_paystack_payment       
      ios:
        default_package: flutter_paystack_payment  
      web:
        default_package: flutter_paystack_payment   