name: flutter_paystack_payment
description: A plugin for Payment through Paystack made By Oreofe Solarin. 
version: 0.1.2+5
homepage: https://github.com/peterson-umoke/flutter_paystack_payment

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.18.1
  meta: ^1.7.0
  async: ^2.8.2
  # Required for Dart Encryption 
  basic_utils: ^5.3.0
  pointycastle: ^3.6.0
  # webview_flutter: ^3.0.0

  # For Requests for Device
  platform_info: ^4.0.0
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  webview_flutter: ^4.2.0
  universal_html: ^2.0.8
  credit_card_scanner: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  matcher: ^0.12.11
  mockito: ^5.2.0



flutter:
  assets:
    - assets/images/
  plugin:
    platforms:
      android:
        default_package: flutter_paystack_payment 
      linux:
        default_package: flutter_paystack_payment          
      windows:
        default_package: flutter_paystack_payment       
      ios:
        default_package: flutter_paystack_payment  
      web:
        default_package: flutter_paystack_payment   