name: flutter_paystack_payment
description: A plugin for Payment through Paystack
version: 0.0.1
homepage: https://github.com/DEVSOG12/flutter_paystack_payment

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 
  intl:
  meta: 
  async: 
  # Required for Dart Encryption
  basic_utils:
  pointycastle:
  flutter_inappwebview:
  platform_info:
  device_info:
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
